name: CI / CD
on:
    push:
        branches: [ 'feat/@next' ]
    pull_request:
        branches: [ 'feat/@next' ]
jobs:
    install:
        name: Install
        runs-on: ubuntu-latest
        strategy:
            matrix:
                node-version: [ 16.x ]
        steps:
            -   name: Checkout repository
                uses: actions/checkout@v3
                with:
                    fetch-depth: 2
            -   run: git checkout HEAD^2
                if: ${{ github.event_name == 'pull_request' }}
            -   name: Use Node.js ${{ matrix.node-version }}
                uses: actions/setup-node@v2
                with:
                    node-version: ${{ matrix.node-version }}
            -   name: Install dependencies
                run: npm i
            -   name: Cache node modules
                uses: actions/upload-artifact@v3
                with:
                    name: artifact-node-modules
                    path: node_modules

    linter:
        name: Linter
        runs-on: ubuntu-latest
        needs: [install]
        steps:
            -   name: Checkout repository
                uses: actions/checkout@v3
                with:
                    fetch-depth: 2
            -   run: git checkout HEAD^2
                if: ${{ github.event_name == 'pull_request' }}
            -   uses: actions/download-artifact@v3
                with:
                    name: artifact-node-modules
            -   name: Run linter
                run: npm run lint

    unit_test:
        name: Unit test
        runs-on: ubuntu-latest
        needs: [install]
        steps:
            -   name: Checkout repository
                uses: actions/checkout@v3
                with:
                    fetch-depth: 2
            -   run: git checkout HEAD^2
                if: ${{ github.event_name == 'pull_request' }}
            -   uses: actions/download-artifact@v3
                with:
                    name: artifact-node-modules
            -   name: Run unit test
                run: npm test