name: CI / CD
on:
    push:
        branches: [ 'feat/@next' ]
    pull_request:
        branches: [ 'feat/@next' ]
jobs:
    install:
        name: Install
        runs-on: ubuntu-latest
        strategy:
            matrix:
                node-version: [ 16.x ]
        steps:
            -   name: Checkout repository
                uses: actions/checkout@v3
                with:
                    fetch-depth: 2
            -   run: git checkout HEAD^2
                if: ${{ github.event_name == 'pull_request' }}
            -   name: Configure environment
                run: make dev-env
            -   name: Use Node.js ${{ matrix.node-version }}
                uses: actions/setup-node@v3
                with:
                    node-version: ${{ matrix.node-version }}
            -   name: Install dependencies
                run: npm i
            -   name: Cache node modules
                uses: actions/cache@v3
                id: restore-build
                with:
                    path: ./*
                    key: ${{ github.sha }}

    linter:
        name: Linter
        runs-on: ubuntu-latest
        needs: [install]
        steps:
            -   name: Checkout repository
                uses: actions/checkout@v3
                with:
                    fetch-depth: 2
            -   name: Use Node.js ${{ matrix.node-version }}
                uses: actions/setup-node@v3
                with:
                    node-version: ${{ matrix.node-version }}
            -   uses: actions/cache@v3
                id: restore-build
                with:
                    path: ./*
                    key: ${{ github.sha }}
            -   name: Run linter
                run: npm run lint

    unit_test:
        name: Unit test
        runs-on: ubuntu-latest
        needs: [install]
        steps:
            -   name: Checkout repository
                uses: actions/checkout@v3
                with:
                    fetch-depth: 2
            -   name: Use Node.js ${{ matrix.node-version }}
                uses: actions/setup-node@v3
                with:
                    node-version: ${{ matrix.node-version }}
            -   uses: actions/cache@v3
                id: restore-build
                with:
                    path: ./*
                    key: ${{ github.sha }}
            -   name: Run unit test
                run: npm test